name: ci

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: ${{ inputs.stageName }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Action ci
        uses: ./.github/actions/ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}
